### ISSUE TITLE
Authorization Failed

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/accounts#3]
![image](https://cloud.githubusercontent.com/assets/6858319/9400408/b5329656-4775-11e5-99b4-2f98485be6ef.png)

**Comment by AdamBLevine** [comment]
I was able to recover my existing account and verify my email but this is what happened when I tried to log into the new swapbot interface. This happened in both Chrome and Firefox

**Comment by deweller** [comment]
This was a problem with Tokenly Account usernames that conflicted with existing, manually created swapbot usernames.

Fixed in https://github.com/tokenly/swapbot/commit/944df9630f9c4821ccca7e6ab51f9ab048e41f2c.
